profiles: test_case

server:
  port: 8007
spring:
  datasource:
    url: jdbc:mysql:///yitaijk?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect
logging.level:
  com.shengchuang: debug
  root: warn
#  org.hibernate.SQL: debug #显示SQL
system.image.upload.path: /upload/


