profiles: prd

server:
  port: 8322
logging:
  path: /logs/springboot/
  level: warn
spring:
  datasource:
    url: jdbc:mysql://10.66.88.117/mmd?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username:
    password:

# 上传地址 150.109.38.97:/springboot/mmd_8322