profiles: test

server:
  port: 8040
spring:
  datasource:
    url: jdbc:mysql://150.109.57.151/mmd?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false&serverTimezone=UTC
    username: test
    password:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect
logging.level:
  com.shengchuang: info
  #org.hibernate.SQL: debug #显示SQL


