profiles: dev

server:
  port: 8030
spring:
  datasource:
    url: jdbc:mysql:///shop?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect
logging.level:
  root: warn
  com.shengchuang: debug
  org.hibernate.SQL: debug #显示SQL
  org.springframework.boot.web.embedded.tomcat.TomcatWebServer: info
system.image.upload.path: /upload/


